title: Li Zhijiang's Homepage
page-top-title: Li Zhijiang
top-section-bg-text: Computer Science
home-subtitle: Li Zhijiang&ensp;|&ensp;李治江
copyright-text: '&copy; Li Zhijiang 2025-2035. All Rights Reserved.'
